import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final result = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(result != null, 'AppLocalizations is not initialized');
    return result!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'AI Meditation Guide',
      'nav_home': 'Home',
      'nav_history': 'History',
      'hello': 'Hello, ',
      'how_are_you': 'How are you\n',
      'feeling': 'feeling ',
      'today': 'today?',
      'generate_meditation': 'GENERATE MEDITATION',
      'breathing_exercise': 'BREATHING EXERCISE',
      'daily_routine': 'DAILY ROUTINE',
      'todays_meditation': "Today's Meditation",
      'recommended_sessions': 'Recommended Sessions',
      'sleep': 'SLEEP',
      'stress_anxiety': 'STRESS & ANXIETY',
      'daily_meditation': 'DAILY MEDITATION',
      'minutes_short': '2 MIN',
      'minutes_long': '2 MINUTES',
      'quick_break': 'Take a quick meditation break',
      'deep_sleep': 'Deep Sleep',
      'sleep_breath': 'Sleep Breathing',
      'night_calm': 'Night Calm',
      'dream_prep': 'Dream Prep',
      'bedtime_breath': 'Bedtime Breath',
      'stress_relief': 'Stress Relief',
      'calm_breath': 'Calm Breathing',
      'anxiety_ease': 'Ease Anxiety',
      'panic_relief': 'Quick Calm',
      'inner_peace': 'Inner Peace',
      'tension_release': 'Release Tension',
      'morning_focus': 'Morning Focus',
      'midday_reset': 'Midday Reset',
      'gratitude': 'Gratitude',
      'energy_boost': 'Energy Boost',
      'evening_wind': 'Evening Wind Down',
      'body_scan': 'Body Scan',
      'history_title': 'HISTORY',
      'no_meditations': 'No meditations yet',
      'no_breathing': 'No breathing exercises yet',
      'no_favorites': 'No favorites yet',
      'tab_meditations': 'MEDITATIONS',
      'tab_breathing': 'BREATHING',
      'meditation_type': 'MEDITATION',
      'breathing_type': 'BREATHING',
      'next': 'NEXT',
      'start_now': 'START NOW',
      'onboarding_1_italic': 'Relax & Focus',
      'onboarding_1_bold': 'with AI\nMeditation',
      'onboarding_2_italic': 'AI Creates',
      'onboarding_2_bold': 'Sessions for\nYour Mood',
      'onboarding_3_italic': 'Listen & Follow',
      'onboarding_3_bold': 'AI Guidance',
      'onboarding_4_italic': 'Track Your',
      'onboarding_4_bold': 'Mindfulness &\nProgress',
      'unlock_full': 'Unlock Full',
      'ai_meditation_power': 'AI Meditation Power',
      'paywall_description':
          'Unlimited guided sessions, personalized AI\nmeditations, track your mindfulness.',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'week': 'week',
      'month': 'month',
      'year': 'year',
      'trial_3_days': '3-day trial',
      'save_75': 'Save 75%',
      'restore': 'Restore',
      'subscribe': 'Subscribe',
      'feature_personalized_sessions': 'Personalized Sessions',
      'feature_sleep_relaxation': 'Sleep & Relaxation',
      'feature_focus_energy': 'Focus & Energy',
      'feature_mindfulness_tracking': 'Mindfulness Tracking',
      'feature_nature_music': 'Nature & Music Sounds',
      'start_session': 'START SESSION',
      'start': 'START',
      'mark_as_done': 'MARK AS DONE',
      'routine': 'ROUTINE',
      'daily_routine_intro':
          'Daily Routine helps you maintain balance throughout the day. Here you can generate a personalised practice — from morning meditation to evening relaxation.',
      'meditation_goal': 'MEDITATION GOAL',
      'duration': 'DURATION',
      'voice_style': 'VOICE STYLE',
      'background_sound': 'BACKGROUND SOUND',
      'background_sounds': 'BACKGROUND SOUNDS',
      'background_volume': 'Background Volume',
      'none': 'None',
      'nature': 'Nature',
      'ambient_music': 'Ambient music',
      'rain': 'Rain',
      'generate': 'GENERATE',
      'generate_meditation_title': 'GENERATE MEDITATION',
      'fill_generate_meditation':
          'Fill in the details below to\ngenerate a meditation',
      'fill_generate_breathing':
          'Fill in the details below to\ngenerate a breathing exercise',
      'mood_check_in': 'Mood Check-in',
      'meditation': 'MEDITATION',
      'breathing_exercise_title': 'BREATHING EXERCISE',
      'congrats': 'Congrats!',
      'calm': 'Calm',
      'neutral': 'Neutral',
      'stressed': 'Stressed',
      'anxious': 'Anxious',
      'reduce_stress': 'Reduce stress',
      'improve_sleep': 'Improve sleep',
      'increase_focus': 'Increase focus',
      'boost_energy': 'Boost energy',
      'calm_anxiety': 'Calm anxiety',
      'soft': 'Soft',
      'neutra': 'Neutra',
      'deep': 'Deep',
      'min_1': '1 min',
      'min_3': '3 min',
      'min_5': '5 min',
      'min_10': '10 min',
      'min_15': '15 min',
      'inhale': 'Inhale',
      'exhale': 'Exhale',
      'hold': 'Hold',
      'sec': 'sec.',
      'generating_voice': 'Generating voice...',
      'voice_ready': 'Voice ready',
      'added_to_favorites': 'Added to favorites',
      'removed_from_favorites': 'Removed from favorites',
      'share_meditation': 'Share meditation',
    },
    'ru': {
      'app_title': 'AI Медитация Гид',
      'nav_home': 'Главная',
      'nav_history': 'История',
      'hello': 'Привет, ',
      'how_are_you': 'Как ты\n',
      'feeling': 'чувствуешь ',
      'today': 'себя сегодня?',
      'generate_meditation': 'СОЗДАТЬ МЕДИТАЦИЮ',
      'breathing_exercise': 'ДЫХАТЕЛЬНАЯ ПРАКТИКА',
      'daily_routine': 'ЕЖЕДНЕВНАЯ РУТИНА',
      'todays_meditation': 'Медитация на сегодня',
      'recommended_sessions': 'Рекомендуемые сессии',
      'sleep': 'СОН',
      'stress_anxiety': 'СТРЕСС И ТРЕВОГА',
      'daily_meditation': 'ЕЖЕДНЕВНАЯ МЕДИТАЦИЯ',
      'minutes_short': '2 МИН',
      'minutes_long': '2 МИНУТЫ',
      'quick_break': 'Сделай короткую медитационную паузу',
      'deep_sleep': 'Глубокий сон',
      'sleep_breath': 'Дыхание для сна',
      'night_calm': 'Ночной покой',
      'dream_prep': 'Подготовка ко сну',
      'bedtime_breath': 'Вечернее дыхание',
      'stress_relief': 'Снятие стресса',
      'calm_breath': 'Спокойное дыхание',
      'anxiety_ease': 'Снятие тревоги',
      'panic_relief': 'Быстрое успокоение',
      'inner_peace': 'Внутренний покой',
      'tension_release': 'Снятие напряжения',
      'morning_focus': 'Утренний фокус',
      'midday_reset': 'Дневная перезагрузка',
      'gratitude': 'Благодарность',
      'energy_boost': 'Заряд энергии',
      'evening_wind': 'Вечернее расслабление',
      'body_scan': 'Сканирование тела',
      'history_title': 'ИСТОРИЯ',
      'no_meditations': 'Медитаций пока нет',
      'no_breathing': 'Дыхательных практик пока нет',
      'no_favorites': 'Избранных пока нет',
      'tab_meditations': 'МЕДИТАЦИИ',
      'tab_breathing': 'ДЫХАНИЕ',
      'meditation_type': 'МЕДИТАЦИЯ',
      'breathing_type': 'ДЫХАНИЕ',
      'next': 'ДАЛЕЕ',
      'start_now': 'НАЧАТЬ',
      'onboarding_1_italic': 'Расслабься и сфокусируйся',
      'onboarding_1_bold': 'с AI\nмедитацией',
      'onboarding_2_italic': 'AI создаёт',
      'onboarding_2_bold': 'сессии под\nтвое состояние',
      'onboarding_3_italic': 'Слушай и следуй',
      'onboarding_3_bold': 'AI-наставнику',
      'onboarding_4_italic': 'Отслеживай',
      'onboarding_4_bold': 'осознанность и\nпрогресс',
      'unlock_full': 'Открой всю',
      'ai_meditation_power': 'силу AI-медитации',
      'paywall_description':
          'Неограниченные сессии, персональные AI-медитации и трекинг осознанности.',
      'weekly': 'Неделя',
      'monthly': 'Месяц',
      'yearly': 'Год',
      'week': 'неделю',
      'month': 'месяц',
      'year': 'год',
      'trial_3_days': '3 дня пробно',
      'save_75': 'Скидка 75%',
      'restore': 'Восстановить',
      'subscribe': 'Подписаться',
      'feature_personalized_sessions': 'Персональные сессии',
      'feature_sleep_relaxation': 'Сон и расслабление',
      'feature_focus_energy': 'Фокус и энергия',
      'feature_mindfulness_tracking': 'Трекинг осознанности',
      'feature_nature_music': 'Звуки природы и музыка',
      'start_session': 'НАЧАТЬ СЕССИЮ',
      'start': 'НАЧАТЬ',
      'mark_as_done': 'ОТМЕТИТЬ КАК ВЫПОЛНЕНО',
      'routine': 'РУТИНА',
      'daily_routine_intro':
          'Ежедневная рутина помогает сохранять баланс в течение дня. Здесь можно сгенерировать персональную практику — от утренней медитации до вечернего расслабления.',
      'meditation_goal': 'ЦЕЛЬ МЕДИТАЦИИ',
      'duration': 'ДЛИТЕЛЬНОСТЬ',
      'voice_style': 'СТИЛЬ ГОЛОСА',
      'background_sound': 'ФОНОВЫЙ ЗВУК',
      'background_sounds': 'ФОНОВЫЕ ЗВУКИ',
      'background_volume': 'Громкость фона',
      'none': 'Нет',
      'nature': 'Природа',
      'ambient_music': 'Эмбиент',
      'rain': 'Дождь',
      'generate': 'СОЗДАТЬ',
      'generate_meditation_title': 'СОЗДАТЬ МЕДИТАЦИЮ',
      'fill_generate_meditation':
          'Заполни параметры ниже,\nчтобы создать медитацию',
      'fill_generate_breathing':
          'Заполни параметры ниже,\nчтобы создать дыхательную практику',
      'mood_check_in': 'Состояние',
      'meditation': 'МЕДИТАЦИЯ',
      'breathing_exercise_title': 'ДЫХАТЕЛЬНАЯ ПРАКТИКА',
      'congrats': 'Отлично!',
      'calm': 'Спокойно',
      'neutral': 'Нейтрально',
      'stressed': 'Стресс',
      'anxious': 'Тревожно',
      'reduce_stress': 'Снизить стресс',
      'improve_sleep': 'Улучшить сон',
      'increase_focus': 'Повысить концентрацию',
      'boost_energy': 'Повысить энергию',
      'calm_anxiety': 'Успокоить тревогу',
      'soft': 'Мягкий',
      'neutra': 'Нейтральный',
      'deep': 'Глубокий',
      'min_1': '1 мин',
      'min_3': '3 мин',
      'min_5': '5 мин',
      'min_10': '10 мин',
      'min_15': '15 мин',
      'inhale': 'Вдох',
      'exhale': 'Выдох',
      'hold': 'Задержка',
      'sec': 'сек.',
      'generating_voice': 'Генерация голоса...',
      'voice_ready': 'Голос готов',
      'added_to_favorites': 'Добавлено в избранное',
      'removed_from_favorites': 'Удалено из избранного',
      'share_meditation': 'Поделиться медитацией',
    },
  };

  String t(String key) {
    final languageCode = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
